name: Move-Text CI Tests 

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.1        
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - 29.1
          - snapshot
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Test
      run: |
        emacs --batch \
        -eval "(setq load-prefer-newer t)" \
        -eval "(add-to-list 'load-path \".\")" \
        -l ert \
        -l move-text.el \
        -l move-text-tests.el \
        -f ert-run-tests-batch-and-exit
